package com.subash.user.management.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity class representing a user record in the {@code users} table.
 * <p>
 * This class is used to persist user details such as credentials and contact information.
 */
@Entity
@Table(name = "users")
@Data
public class User {

    /**
     * Primary key identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    /**
     * Unique username for the user.
     * Used for login and identification.
     */
    @Column(name = "username", unique = true, nullable = false)
    private String username;

    /**
     * Encrypted password stored as a hash.
     * This should not be exposed or used directly for authentication logic.
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /**
     * Role assigned to the user (e.g., ADMIN or USER).
     * Enum is stored as a string in the database.
     */
    @Column(name = "role", nullable = false)
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * Email address of the user.
     * Must be unique but is optional.
     */
    @Column(name = "email_id", unique = true)
    private String emailId;

    /**
     * Contact phone number of the user.
     * This field is optional.
     */
    @Column(name = "phone_number")
    private String phoneNumber;

}
