spring:
  application:
    name: user-management

  #Updated the datasource properties as per DB details
  datasource:
    url: jdbc:postgresql://localhost:5432/mutual_fund_management
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

print:
  log:
    enable:
      request: true
      response: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
